In [0]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [0]:
train=pd.read_csv('/content/train.csv')
test=pd.read_csv('/content/train.csv')
sample=pd.read_csv('/content/sample_submission.csv')

In [15]:
print(train.shape)
print(test.shape)
print(sample.shape)

(2290, 785)
(2290, 785)
(28000, 2)


In [0]:
print(train.isnull().sum())
print(test.isnull().sum())
print(sample.isnull().sum())

In [29]:
train.dropna(inplace=True)
test.dropna(inplace=True)
print(train.shape)
print(test.shape)

(2289, 785)
(2289, 785)


In [0]:
var=pd.concat([train,test],axis=0)

In [54]:
var.shape

(4578, 785)

In [28]:
X=train.iloc[:,1:]
print(X.shape)
y=train['label']
print(y.shape)

(2289, 784)
(2289,)


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [0]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=1000,criterion='entropy',random_state=0)

In [110]:
model

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [111]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [130]:
y_pred=model.predict(X_test)
print(y_pred)

[8 7 6 ... 0 2 5]


In [0]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [131]:
#cm=confusion_matrix(y_pred,y_test)
ac=accuracy_score(y_pred,y_test)
#print(cm)
print(ac)

0.9880357142857142


In [0]:
var1=var
var2=var
var3=var
var4=var
var5=var
var6=var

In [0]:
var7=pd.concat([var1,var2],axis=0)
var8=pd.concat([var3,var4],axis=0)
var9=pd.concat([var5,var6],axis=0)
var10=pd.concat([var7,var8],axis=0)
var11=pd.concat([var9,var10],axis=0)
var12=pd.concat([var,var11],axis=0)

In [89]:
print(var12.shape)
z_pred=var12.iloc[:28000,1:]
print(z_pred.shape)
print(sample.shape)

(32046, 785)
(28000, 784)
(28000, 2)


In [0]:
#Submitting the MODEL in Kaggle
pred=pd.DataFrame(y_pred)
sample=pd.read_csv('/content/sample_submission.csv')
datasets=pd.concat([sample['ImageId'],pred],axis=1)
datasets.columns=['ImageId','Label']
datasets.to_csv('final_sub.csv',index=False)

In [117]:
var_final=var12.iloc[:28000,:]
print(var_final.shape)

(28000, 785)


In [0]:
X=var_final.iloc[:,1:]
y=var_final['label']

In [121]:
print(X.shape)
print(y.shape)

(28000, 784)
(28000,)


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [124]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'he_uniform',activation='relu',input_dim = 784))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'he_uniform',activation='relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'glorot_uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=784, units=6, kernel_initializer="he_uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="he_uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="glorot_uniform")`
  if __name__ == '__main__':


In [125]:
# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, nb_epoch = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.





Train on 15007 samples, validate on 7393 samples
Epoch 1/100





15007/15007 [==============================] - 16s 1ms/step - loss: -54.2530 - acc: 0.1121 - val_loss: -53.8673 - val_acc: 0.1146
Epoch 2/100
15007/15007 [==============================] - 8s 511us/step - loss: -54.3063 - acc: 0.1121 - val_loss: -53.8673 - val_acc: 0.1146
Epoch 3/100
15007/15007 [==============================] - 8s 508us/step - loss: -54.3063 - acc: 0.1121 - val_loss: -53.8673 - val_acc: 0.1146
Epoch 4/100
15007/15007 [==============================] - 8s 516us/step - loss: -54.3063 - acc: 0.1121 - val_loss: -53.8673 - val_acc: 0.1146
Epoch 5/100
15007/15007 [==============================] - 8s 517us/step - loss: -54.3063 - acc: 0.1121 - val_loss: -53.8673 - val_acc: 0.1146
Epoch 6/100
15007/15007 [==============================] - 8s 507us/step - loss: -54.3063 - acc: 0.1121 - val_loss: -53.8673 - val_acc: 0.1146
Epoch 7/100
15007/15007 [==============================] - 8s 514us/step - loss: -54.3

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
#y_pred = (y_pred > 0.5)

In [132]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

print(cm)
print()
print(score)

[[549   0   0   0   0   2   8   0   0   0]
 [  0 638   0   0   4   2   0   0   0   0]
 [  0   1 611   0   0   0   0   1   0   0]
 [  0   0   2 484   0   0   0   0   1   0]
 [  0   0   0   0 543   0   0   0   0   2]
 [  0   0   1   5   0 510   0   0   0   0]
 [  0   0   1   0   0   0 577   0   2   0]
 [  0   5   2   0   0   0   0 524   0   6]
 [  0   1   0   7   0   0   0   0 507   8]
 [  3   0   0   0   3   0   0   0   0 590]]

0.9880357142857142


In [0]:
qwerty=var_final.iloc[:,1:]

In [0]:
y_pred = classifier.predict(qwerty)

In [139]:
len(y_pred)

28000

In [0]:
#Submitting the MODEL in Kaggle
pred=pd.DataFrame(y_pred)
sample=pd.read_csv('/content/sample_submission.csv')
datasets=pd.concat([sample['ImageId'],pred],axis=1)
datasets.columns=['ImageId','Label']
datasets.to_csv('final_ann.csv',index=False)